# Generated by Django 3.2.15 on 2022-09-23 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_socialaccount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='socialaccount',
            name='account_created_date',
            field=models.DateTimeField(null=True),
        ),
    ]
