# Generated by Django 3.2.15 on 2022-10-02 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_auto_20221002_1106'),
    ]

    operations = [
        migrations.AlterField(
            model_name='socialaccount',
            name='account_user_id',
            field=models.CharField(max_length=255),
        ),
    ]
