# Generated by Django 3.2.15 on 2022-10-09 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_alter_socialaccount_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='source',
            field=models.CharField(choices=[('google', 'google'), ('custom', 'custom')], default='custom', max_length=20),
        ),
    ]
